export const eventNavItems = [
  {
    id: 'reels',
    labelKey: 'nav.reels',
    fallbackLabel: 'Reels',
    path: '/reels',
    mobilePath: '/mobile/reels',
    icon: 'Play',
    color: '#f472b6',
    subtitle: 'Short fashion drops',
  },
  {
    id: 'style-feed',
    labelKey: 'nav.community',
    fallbackLabel: 'Style Feed',
    path: '/style-feed',
    mobilePath: '/mobile/style-feed',
    icon: 'Camera',
    color: '#c9b8ff',
    subtitle: 'Obraz galereyasi',
  },
  {
    id: 'challenges',
    labelKey: 'nav.challenges',
    fallbackLabel: 'Challenges',
    path: '/challenges',
    mobilePath: '/mobile/challenges',
    icon: 'Swords',
    color: '#a8d8ea',
    subtitle: 'Musobaqalar',
  },
  {
    id: 'live',
    labelKey: 'nav.live',
    fallbackLabel: 'Jonli Efir',
    path: '/live',
    mobilePath: '/mobile/live',
    icon: 'Radio',
    color: '#ef4444',
    subtitle: 'Live Commerce',
  },
  {
    id: 'vip-club',
    labelKey: 'nav.vipClub',
    fallbackLabel: 'VIP Club',
    path: '/vip-club',
    mobilePath: '/mobile/vip-club',
    icon: 'Crown',
    color: '#d6b47c',
    subtitle: 'Ball va imtiyozlar',
  },
  {
    id: 'eco-impact',
    labelKey: 'nav.ecoImpact',
    fallbackLabel: 'Eco Impact',
    path: '/eco-impact',
    mobilePath: '/mobile/eco-impact',
    icon: 'Leaf',
    color: '#4ade80',
    subtitle: 'Tabiatga hissa',
  },
  {
    id: 'gift-cards',
    labelKey: 'nav.giftCard',
    fallbackLabel: "Sovg'a kartalari",
    path: '/gift-cards',
    mobilePath: '/mobile/gift-cards',
    icon: 'Gift',
    color: '#fb923c',
    subtitle: "Premium sovg'alar",
  },
  {
    id: 'blog',
    labelKey: 'nav.blog',
    fallbackLabel: 'Fashion Blog',
    path: '/blog',
    mobilePath: '/mobile/blog',
    icon: 'MessageSquare',
    color: '#f472b6',
    subtitle: 'Trendlar va stil',
  },
];

export const resolveNavLabel = (item, t) => t(item.labelKey, item.fallbackLabel);
